using System.Globalization;

namespace YouTube.Models
{
    public class ClosedCaptionInfo
    {
        public CultureInfo Language { get; set; }
        public string Url { get; set; }
        public bool AutoGenerated { get; set; }
    }
}
